# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  enviro365assessmentgraddotnetversion:
    image: enviro365assessmentgraddotnetversion
    build:
      context: .
      dockerfile: Enviro365Assessment_Grad_DOTNET_version/Dockerfile
    ports:
      - 5244:5244
