// <auto-generated />
using Enviro365Assessment_Grad_DOTNET_version.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enviro365Assessment_Grad_DOTNET_version.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240417004111_InitiaCreate")]
    partial class InitiaCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enviro365Assessment_Grad_DOTNET_version.Model.Waste", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("waste_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("waste_category");

                    b.Property<string>("Disposalguideline")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("disposal_guideline");

                    b.Property<string>("Recyclingtips")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("recycling_tips");

                    b.HasKey("Id");

                    b.ToTable("Waste");
                });
#pragma warning restore 612, 618
        }
    }
}
